defaults: &defaults
  website: "Unindented"
  author:  "Daniel Perez Alvarez"
  email:   "daniel@unindented.org"
  twitter: "unindented"
  github:  "unindented"

  processors:
    kramdown:
      enable_coderay: false
    nokogiri:
      css: "table"
    pygments:
      misc:
        cssclass: "highlighted"

  mathjax:
    url: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    config:
      message_style: "none"

  webfonts:
    url: "//ajax.googleapis.com/ajax/libs/webfont/1.5.2/webfont.js"
    config:
      google:
        families:
          "Dosis":
            - "700"
          "Source Sans Pro":
            - "400"
            - "600"
            - "400italic"
            - "600italic"
          "Source Code Pro":
            - "400"
            - "600"

  fixurl:
    url: "//linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"

  tagman:
    url_nojs: "//www.googletagmanager.com/ns.html"
    url_js:   "//www.googletagmanager.com/gtm.js"
    id:       "GTM-WFGVBN"

test:
  <<: *defaults

  host: "http://test.unindented.org"

development:
  <<: *defaults

  host: "http://dev.unindented.org"

  build:
    port: "3001"
    destination: "unindented:/home/unindented/dev.unindented.org/"

production:
  <<: *defaults

  host: "http://unindented.org"

  build:
    port: "3001"
    destination: "unindented:/home/unindented/unindented.org/"
